wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.27.2
    framework: huggingface
    huggingface_version: 5.12.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1782217717
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 71
      - 84
      2:
      - 1
      - 11
      - 49
      - 51
      - 71
      - 84
      3:
      - 2
      - 4
      - 7
      - 13
      - 16
      - 19
      - 42
      - 62
      - 66
      4: 3.11.7
      5: 0.27.2
      6: 5.12.1
      9:
        1: transformers_trainer
      13: linux-x86_64
    e:
      0c2bmznsucatynlgey834r0jymd55b1s:
        os: Linux-4.18.0-553.6.1.el8.x86_64-x86_64-with-glibc2.28
        python: CPython 3.11.7
        started_at: '2026-06-23T12:28:34.327998Z'
        args:
        - --run_name
        - default_fullepoch
        program: /nas3/chichi418/535510-Reinforcement-Learning/hw/hw4/train_dpo.py
        code_path: hw/hw4/train_dpo.py
        code_path_local: train_dpo.py
        git:
          remote_url: https://github.com/chichi0418/535510-Reinforcement-Learning.git
          commit: 7bf52f6c99446eb9a3ed5435a4bdd09a47af5537
        root: /nas3/chichi418/535510-Reinforcement-Learning/hw/hw4
        host: eda17
        executable: /nas3/chichi418/535510-Reinforcement-Learning/hw/hw4/.venv/bin/python
        cpu_count: 48
        cpu_count_logical: 96
        gpu_type: NVIDIA TITAN V
        gpu_count: 1
        disk:
          /:
            total: '242974773248'
            used: '176248791040'
        memory:
          total: '269544013824'
        gpu_nvidia:
        - name: NVIDIA TITAN V
          memory_total: '12884901888'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-956b0990-5999-6bba-e81c-937e855dff28
        cuda_version: '13.0'
        writer_id: 0c2bmznsucatynlgey834r0jymd55b1s
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/logps/chosen
      5: 1
      6:
      - 1
    - 1: train/entropy
      5: 1
      6:
      - 1
    - 1: train/mean_token_accuracy
      5: 1
      6:
      - 1
    - 1: train/rewards/chosen
      5: 1
      6:
      - 1
    - 1: train/rewards/accuracies
      5: 1
      6:
      - 1
    - 1: train/rewards/rejected
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: train/rewards/margins
      5: 1
      6:
      - 1
    - 1: train/logps/rejected
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/logits/chosen
      5: 1
      6:
      - 1
    - 1: train/logits/rejected
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/num_tokens
      5: 1
      6:
      - 1
    - 1: eval/rewards/accuracies
      5: 1
      6:
      - 1
    - 1: eval/entropy
      5: 1
      6:
      - 1
    - 1: eval/num_tokens
      5: 1
      6:
      - 1
    - 1: eval/logits/rejected
      5: 1
      6:
      - 1
    - 1: eval/rewards/margins
      5: 1
      6:
      - 1
    - 1: eval/rewards/chosen
      5: 1
      6:
      - 1
    - 1: eval/rewards/rejected
      5: 1
      6:
      - 1
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/logits/chosen
      5: 1
      6:
      - 1
    - 1: eval/logps/chosen
      5: 1
      6:
      - 1
    - 1: eval/logps/rejected
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
    - 1: eval/mean_token_accuracy
      5: 1
      6:
      - 1
model:
  desc: null
  value: Qwen/Qwen2.5-0.5B-Instruct
beta:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 5.0e-07
per_device_train_batch_size:
  desc: null
  value: 1
gradient_accumulation_steps:
  desc: null
  value: 8
num_train_epochs:
  desc: null
  value: 1
max_length:
  desc: null
  value: 1024
avg_chosen_token_length:
  desc: null
  value: 271.9
avg_rejected_token_length:
  desc: null
  value: 245.4
transformers_version:
  desc: null
  value: 5.12.1
architectures:
  desc: null
  value:
  - Qwen2ForCausalLM
output_hidden_states:
  desc: null
  value: false
return_dict:
  desc: null
  value: true
dtype:
  desc: null
  value: float32
chunk_size_feed_forward:
  desc: null
  value: 0
is_encoder_decoder:
  desc: null
  value: false
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
problem_type:
  desc: null
  value: null
vocab_size:
  desc: null
  value: 151936
hidden_size:
  desc: null
  value: 896
intermediate_size:
  desc: null
  value: 4864
num_hidden_layers:
  desc: null
  value: 24
num_attention_heads:
  desc: null
  value: 14
num_key_value_heads:
  desc: null
  value: 2
hidden_act:
  desc: null
  value: silu
max_position_embeddings:
  desc: null
  value: 32768
initializer_range:
  desc: null
  value: 0.02
rms_norm_eps:
  desc: null
  value: 1.0e-06
use_cache:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
rope_parameters:
  desc: null
  value:
    rope_theta: 1000000.0
    rope_type: default
use_sliding_window:
  desc: null
  value: false
sliding_window:
  desc: null
  value: null
max_window_layers:
  desc: null
  value: 21
layer_types:
  desc: null
  value:
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
attention_dropout:
  desc: null
  value: 0.0
pad_token_id:
  desc: null
  value: 151643
bos_token_id:
  desc: null
  value: null
eos_token_id:
  desc: null
  value: 151645
_name_or_path:
  desc: null
  value: Qwen/Qwen2.5-0.5B-Instruct
model_type:
  desc: null
  value: qwen2
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: dpo-default_fullepoch
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
lr_scheduler_kwargs:
  desc: null
  value: null
warmup_steps:
  desc: null
  value: 0
optim:
  desc: null
  value: adafactor
optim_args:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
optim_target_modules:
  desc: null
  value: null
average_tokens_across_devices:
  desc: null
  value: true
max_grad_norm:
  desc: null
  value: 1.0
label_smoothing_factor:
  desc: null
  value: 0.0
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: true
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
gradient_checkpointing:
  desc: null
  value: true
gradient_checkpointing_kwargs:
  desc: null
  value:
    use_reentrant: false
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
use_liger_kernel:
  desc: null
  value: false
liger_kernel_config:
  desc: null
  value: null
neftune_noise_alpha:
  desc: null
  value: null
torch_empty_cache_steps:
  desc: null
  value: null
auto_find_batch_size:
  desc: null
  value: false
logging_strategy:
  desc: null
  value: steps
logging_steps:
  desc: null
  value: 25
logging_first_step:
  desc: null
  value: false
log_on_each_node:
  desc: null
  value: true
logging_nan_inf_filter:
  desc: null
  value: true
include_num_input_tokens_seen:
  desc: null
  value: 'no'
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
disable_tqdm:
  desc: null
  value: false
report_to:
  desc: null
  value:
  - wandb
run_name:
  desc: null
  value: default_fullepoch
project:
  desc: null
  value: huggingface
trackio_space_id:
  desc: null
  value: null
trackio_bucket_id:
  desc: null
  value: null
trackio_static_space_id:
  desc: null
  value: null
eval_strategy:
  desc: null
  value: steps
eval_steps:
  desc: null
  value: 250
eval_delay:
  desc: null
  value: 0
per_device_eval_batch_size:
  desc: null
  value: 1
prediction_loss_only:
  desc: null
  value: false
eval_on_start:
  desc: null
  value: false
eval_do_concat_batches:
  desc: null
  value: true
eval_use_gather_object:
  desc: null
  value: false
eval_accumulation_steps:
  desc: null
  value: null
include_for_metrics:
  desc: null
  value: []
batch_eval_metrics:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
save_strategy:
  desc: null
  value: epoch
save_steps:
  desc: null
  value: 500
save_on_each_node:
  desc: null
  value: false
save_total_limit:
  desc: null
  value: null
enable_jit_checkpoint:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_always_push:
  desc: null
  value: false
hub_revision:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
restore_callback_states_from_checkpoint:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
use_cpu:
  desc: null
  value: false
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
parallelism_config:
  desc: null
  value: null
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
dataloader_prefetch_factor:
  desc: null
  value: null
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
train_sampling_strategy:
  desc: null
  value: random
length_column_name:
  desc: null
  value: length
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
ddp_static_graph:
  desc: null
  value: null
ddp_backend:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
fsdp:
  desc: null
  value: null
fsdp_config:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
debug:
  desc: null
  value: []
skip_memory_metrics:
  desc: null
  value: true
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
warmup_ratio:
  desc: null
  value: null
logging_dir:
  desc: null
  value: null
local_rank:
  desc: null
  value: -1
model_init_kwargs:
  desc: null
  value: null
disable_dropout:
  desc: null
  value: true
dataset_num_proc:
  desc: null
  value: null
truncation_mode:
  desc: null
  value: keep_start
padding_free:
  desc: null
  value: false
pad_to_multiple_of:
  desc: null
  value: null
precompute_ref_log_probs:
  desc: null
  value: false
precompute_ref_batch_size:
  desc: null
  value: null
loss_type:
  desc: null
  value:
  - sigmoid
loss_weights:
  desc: null
  value: null
ld_alpha:
  desc: null
  value: null
f_divergence_type:
  desc: null
  value: reverse_kl
f_alpha_divergence_coef:
  desc: null
  value: 0.5
label_smoothing:
  desc: null
  value: 0.0
use_weighting:
  desc: null
  value: false
discopop_tau:
  desc: null
  value: 0.05
activation_offloading:
  desc: null
  value: false
sync_ref_model:
  desc: null
  value: false
ref_model_mixup_alpha:
  desc: null
  value: 0.6
ref_model_sync_steps:
  desc: null
  value: 512
pad_token:
  desc: null
  value: <PAD_TOKEN>
model/num_parameters:
  desc: null
  value: 494032768
